SimaxCrm/Controllers/LeadController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SimaxCrm.Model.Entity;
using SimaxCrm.Model.Enum;
using SimaxCrm.Model.ResponseModel;
using SimaxCrm.Service.Interface;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SimaxCrm.Controllers
{
    public class LeadController : BaseController
    {
        private readonly ILeadService _leadService;
        private readonly ILeadSourceService _leadSourceService;
        private readonly ILeadLanguageService _leadLanguageService;
        private readonly ILeadTagService _leadTagService;
        private readonly ILeadTagMappingService _leadTagMappingService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILeadAutoAssignLogService _leadAutoAssignLogService;
        private readonly IHelperService _helperService;

        public LeadController(
            ILeadService leadService,
            ILeadSourceService leadSourceService,
            ILeadLanguageService leadLanguageService,
            ILeadTagService leadTagService,
            ILeadTagMappingService leadTagMappingService,
            UserManager<ApplicationUser> userManager,
            IHelperService helperService,
            ILeadAutoAssignLogService leadAutoAssignLogService
            )
        {
            _helperService = helperService;
            _leadService = leadService;
            _leadSourceService = leadSourceService;
            _leadLanguageService = leadLanguageService;
            _leadTagService = leadTagService;
            _leadTagMappingService = leadTagMappingService;
            _userManager = userManager;
            _leadAutoAssignLogService = leadAutoAssignLogService;
        }

        // GET: ServiceType
        public IActionResult Index()
        {
            var leads = _leadService.List();
            return View(leads);
        }

        // GET: ServiceType/Create
        public IActionResult Create()
        {
            ViewBag.LeadSourceId = new SelectList(_leadSourceService.List().Where(m => m.Status).ToList(), "Id", "Name");
            ViewBag.LeadLanguageId = new SelectList(_leadLanguageService.List().Where(m => m.Status).ToList(), "Id", "Name");
            ViewBag.LeadTagId = new SelectList(_leadTagService.List().Where(m => m.Status).ToList(), "Id", "Name");
            ViewBag.UserId = new SelectList(getAgentList(), "Id", "Name");
            return View();
        }


        private void setDefaultData()
        {
            ViewBag.LeadSourceId = new SelectList(_leadSourceService.List().Where(m => m.Status).ToList(), "Id", "Name");
            ViewBag.LeadLanguageId = new SelectList(_leadLanguageService.List().Where(m => m.Status).ToList(), "Id", "Name");
            ViewBag.LeadTagId = new SelectList(_leadTagService.List().Where(m => m.Status).ToList(), "Id", "Name");
            ViewBag.UserId = new SelectList(getAgentList(), "Id", "Name");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Lead obj)
        {
            if (ModelState.IsValid)
            {
                bool isAutoAssign = false;

                if (_leadService.IsAny(m => m.PhoneNumber == obj.PhoneNumber))
                {
                    setDefaultData();
                    ModelState.AddModelError("PhoneNumber", "Phone number already exists");
                    return View(obj);
                }

                if (_leadService.IsAny(m => m.Email == obj.Email))
                {
                    setDefaultData();
                    ModelState.AddModelError("Email", "Email already exists");
                    return View(obj);
                }

                if (obj.UserId == "Auto")
                {
                    isAutoAssign = true;
                    var userId = _helperService.AssignAgentSourceAndRankingWise(obj.LeadSourceId);
                    if (string.IsNullOrEmpty(userId))
                    {
                        ModelState.AddModelError("UserId", "No user available for lead auto assign");
                        setDefaultData();
                        return View(obj);
                    }
                    obj.UserId = userId;
                }

                obj.CreatedDate = DateTime.Now;
                obj.AssignedDate = DateTime.Now;
                obj.LeadStatus = LeadStatusType.NewLead.ToString();
                _leadService.Create(obj);

                if (isAutoAssign)
                {
                    var leadAutoAssignLog = new LeadAutoAssignLog()
                    {
                        Id = 0,
                        LeadId = obj.Id,
                        LeadSourceId = obj.LeadSourceId,
                        UserId = obj.UserId,
                        CreatedDate = DateTime.Now
                    };
                    _leadAutoAssignLogService.Create(leadAutoAssignLog);
                }

                if (!string.IsNullOrEmpty(obj.LeadTags))
                {
                    foreach (var item in obj.LeadTags.Split(','))
                    {
                        var leadTagMapping = new LeadTagMapping()
                        {
                            Id = 0,
                            LeadId = obj.Id,
                            LeadTagId = int.Parse(item),
                            CreatedDate = DateTime.Now,
                            Status = true,
                        };
                        _leadTagMappingService.Create(leadTagMapping);
                    }
                }

                ViewBag.Result = "Lead Saved Successfully, Lead Id: " + obj.Id;
                setDefaultData();
                ModelState.Clear();
                return View(new Lead());
            }
            setDefaultData();
            return View(obj);
        }

        private List<ApplicationUser> getAgentList()
        {
            var tid = base.getTidFromClaim();
            var users = _userManager.Users.Where(m => m.Tid == tid).Include(u => u.UserRoles).ThenInclude(ur => ur.Role).ToList();
            return users.Where(m => m.UserRoles.Any(m => m.Role.Name == UserType.Agent.ToString())).ToList();
        }

        public IActionResult Edit(int id)
        {
            var obj = _leadService.ById(id);
            if (obj == null)
            {
                return NotFound();
            }

            ViewBag.LeadSourceId = new SelectList(_leadSourceService.List().Where(m => m.Status).ToList(), "Id", "Name");
            ViewBag.LeadLanguageId = new SelectList(_leadLanguageService.List().Where(m => m.Status).ToList(), "Id", "Name");
            ViewBag.LeadTagId = new SelectList(_leadTagService.List().Where(m => m.Status).ToList(), "Id", "Name");
            ViewBag.UserId = new SelectList(getAgentList(), "Id", "Name");

            return View(obj);
        }

        [HttpPost]
        public JsonResult Edit(int id, Lead obj)
        {
            var result = new BaseResponse<string>();
            if (ModelState.IsValid)
            {
                if (_leadService.IsAny(m => m.PhoneNumber == obj.PhoneNumber && m.Id != id))
                {
                    result.Success = false;
                    result.Response = "Phone number already exists";
                    return Json(result);
                }

                if (_leadService.IsAny(m => m.Email == obj.Email && m.Id != id))
                {
                    result.Success = false;
                    result.Response = "Email already exists";
                    return Json(result);
                }

                var existingLead = _leadService.ById(id);
                existingLead.Address = obj.Address;
                existingLead.City = obj.City;
                existingLead.Country = obj.Country;
                existingLead.Email = obj.Email;
                existingLead.LeadLanguageId = obj.LeadLanguageId;
                existingLead.LeadSourceId = obj.LeadSourceId;
                existingLead.Name = obj.Name;
                existingLead.PhoneNumber = obj.PhoneNumber;
                existingLead.PostalCode = obj.PostalCode;
                existingLead.State = obj.State;
                existingLead.UpdatedDate = DateTime.Now;
                existingLead.UserId = obj.UserId;
                _leadService.Update(existingLead);

                var existingLeadTagMapping = _leadTagMappingService.ByLeadId(id);
                foreach (var leadTagMapping in existingLeadTagMapping)
                {
                    _leadTagMappingService.Delete(leadTagMapping.Id);
                }

                if (!string.IsNullOrEmpty(obj.LeadTags))
                {
                    foreach (var item in obj.LeadTags.Split(','))
                    {
                        var leadTagMapping = new LeadTagMapping()
                        {
                            Id = 0,
                            LeadId = obj.Id,
                            LeadTagId = int.Parse(item),
                            CreatedDate = DateTime.Now,
                            Status = true,
                        };
                        _leadTagMappingService.Create(leadTagMapping);
                    }
                }

                result.Success = true;
                return Json(result);
            }
            result.Success = false;
            var errors = string.Join(",", ModelState.Values.SelectMany(v => v.Errors).ToList().Select(x => x.ErrorMessage).Distinct().ToList());
            result.Response = errors;
            return Json(result);
        }

        // POST: ServiceType/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _leadService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

SimaxCrm/Views/View/Lead.cshtml
@model SimaxCrm.Model.Entity.Lead

@{
    ViewData["Title"] = "Lead View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-4">
        <div class="card">

            <div class="card-header">
                <strong>Update Remarks</strong>
            </div>

            <div class="card-body">
                <partial name="_remarks" model="new SimaxCrm.Model.Entity.CallLog()" />
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="card" style="margin-bottom:0">
            <div>
                <ul class="nav nav-tabs tabs-head" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#lead" role="tab" aria-controls="lead">Lead Info</a>
                    </li>
                    <li class="nav-item">
                        @{var callLogCount = Model.CallLog == null ? 0 : Model.CallLog.Count;}
                        <a class="nav-link" data-toggle="tab" href="#calllog" role="tab" aria-controls="calllog">Call History (@callLogCount)</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#message" role="tab" aria-controls="messages">Send Messages or Email</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="lead" role="tabpanel">
                        <form id="formLead" asp-controller="Lead" asp-action="Edit">
                            <div id="divLeadErrorSummary" class="alert" asp-validation-summary="All"></div>
                            <div class="row">
                                <input type="hidden" asp-for="Id" />
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label asp-for="Name" class="control-label"></label><input asp-for="Name" class="form-control" />
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="LeadLanguageId" class="control-label"></label>
                                        <select style="height:35px" asp-for="LeadLanguageId" class="form-control" asp-items="ViewBag.LeadLanguageId">
                                            <option value=""></option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="LeadTags" class="control-label"></label>
                                        <input asp-for="LeadTags" class="control-label" type="hidden" />
                                        <select class="multipleSelect form-control" multiple style="height:35px" id="LeadTagMulti" name="LeadTagMulti" asp-items="ViewBag.LeadTagId">
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Address" class="control-label"></label><input asp-for="Address" class="form-control" />
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label asp-for="Country" class="control-label"></label><input asp-for="Country" class="form-control" />
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="State" class="control-label"></label><input asp-for="State" class="form-control" />
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="City" class="control-label"></label><input asp-for="City" class="form-control" />
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="PostalCode" class="control-label"></label><input asp-for="PostalCode" class="form-control" />
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label asp-for="PhoneNumber" class="control-label"></label><input readonly="readonly" asp-for="PhoneNumber" class="form-control" />
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Email" class="control-label"></label><input readonly="readonly" asp-for="Email" class="form-control" />
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="LeadSourceId" class="control-label"></label>
                                        <input type="hidden" asp-for="LeadSourceId" />
                                        <select style="height:35px" disabled="disabled" asp-for="LeadSourceId" class="form-control" asp-items="ViewBag.LeadSourceId">
                                            <option value=""></option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="UserId" class="control-label"></label>
                                        <input type="hidden" asp-for="UserId" />
                                        <select style="height:35px" asp-for="UserId" disabled="disabled" class="form-control" asp-items="ViewBag.UserId">
                                            <option value=""></option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="submit" value="Update Lead Data" onclick="return processData()" class="btn btn-primary" />
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="tab-pane" id="calllog" role="tabpanel">

                        @if (Model.CallLog != null)
                        {

                            <table class="table table-responsive-sm">
                                <thead>
                                    <tr>
                                        <th>Dated</th>
                                        <th>Status</th>
                                        <th>Remarks</th>
                                        <th>Message</th>
                                        <th>Start Time</th>
                                        <th>End Time</th>
                                        <th>User</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.CallLog.OrderByDescending(m => m.Id))
                                    {
                                        <tr>
                                            <td>@item.CreatedDate.ToString("dd/MM/yyyy")</td>
                                            <td>@item.Status</td>
                                            <td>@item.Remarks</td>
                                            <td>@item.Message</td>
                                            <td>@item.StartTime.ToFormat("hh:mm tt")</td>
                                            <td>@item.EndTime.ToFormat("hh:mm tt")</td>
                                            <td>@item.User.Name</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }

                    </div>
                    <div class="tab-pane" id="message" role="tabpanel">
                        <partial name="_send-sms-email" model="new SimaxCrm.Model.RequestModel.SendTextModel()" />
                    </div>
                </div>
            </div>

            <div class="card-body">

            </div>
        </div>



    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        var leadJson = null;
        $(document).ready(function () {

            $("#formLead").submit(function (e) {
                updateLead(e);
            });

            leadJson = JSON.parse('@Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model, Newtonsoft.Json.Formatting.None,
                        new Newtonsoft.Json.JsonSerializerSettings()
                        {
                            ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
                        }))');


            var tagIds = '@string.Join(',', Model.LeadTagMapping.Select(m=>m.LeadTagId).Distinct().ToArray())';
            $.each(tagIds.split(','), function (i, v) {
                $('#LeadTagMulti option[value='+ v +']').attr('selected', 'selected');
            });

        });



        function processData() {
            var leadTags = helper.getFastSelectValue('LeadTagMulti');
            $("#LeadTags").val(leadTags);
            return true;
        }

        function updateLead(e) {
            e.preventDefault();
            if ($('#formLead').valid()) {
                var formData = helper.getFormData($("#formLead"));
                ajaxFormPost($("#formLead").attr('action'), formData, function (data) {
                    if (!data.success) {
                        helper.addErrorInForm('divLeadErrorSummary', data.response.split(','));
                    }
                    else {
                        helper.addSuccessInForm('divLeadErrorSummary', ["Lead Updated Successfully"]);
                    }
                });
            }
            else {
                $("#divLeadErrorSummary").addClass("alert-danger");
                helper.clearMessage('divLeadErrorSummary');
            }
        }


    </script>

}